import './globals.css'
import type { Metadata } from 'next'
import { Bebas_Neue } from 'next/font/google'

const inter = Bebas_Neue({subsets: ['latin'],weight: '400'})

export const metadata: Metadata = {
  title: 'Fang Bim',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/kids.png' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
